# Generated by Django 5.2 on 2025-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('top_selling', 'Top Selling'), ('trending', 'Trending Products'), ('recent', 'Recently Added'), ('top_rated', 'Top Rated'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
