# Generated by Django 5.1.7 on 2025-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=999999999),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=999999999),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='20.00', max_digits=999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=999999999),
        ),
    ]
