# Generated by Django 5.1.7 on 2025-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productreview_sentiment_alter_cartorder_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='polarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
